const allTablesSQL = [
`CREATE TABLE IF NOT EXISTS "assignments" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_id" INTEGER,
    "item_name" TEXT NOT NULL,
    "quantity" INTEGER DEFAULT 1,
    "assigned_to" TEXT,
    "department" TEXT,
    "start_date" DATETIME NOT NULL,
    "end_date" DATETIME,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "assignments_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "companies" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER,
    "name" TEXT NOT NULL,
    "tax_number" TEXT,
    "tax_office" TEXT,
    "sgk_no" TEXT,
    "address" TEXT,
    "phone" TEXT,
    "signature_path" TEXT,
    "stamp_path" TEXT,
    "plan" TEXT DEFAULT 'PRO',
    "status" TEXT DEFAULT 'active',
    "expires_at" DATETIME,
    "max_vehicles" INTEGER DEFAULT 50,
    "max_employees" INTEGER DEFAULT 50,
    "max_users" INTEGER DEFAULT 10,
    "storage_limit_mb" INTEGER DEFAULT 1024,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "companies_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "customers" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "email" TEXT,
    "address" TEXT,
    "tax_number" TEXT,
    "tax_office" TEXT,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "customers_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "documents" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_id" INTEGER,
    "related_type" TEXT,
    "related_id" INTEGER,
    "file_name" TEXT NOT NULL,
    "file_path" TEXT NOT NULL,
    "file_type" TEXT,
    "doc_type" TEXT,
    "category" TEXT,
    "folder" TEXT,
    "start_date" DATETIME,
    "end_date" DATETIME,
    "is_archived" INTEGER DEFAULT 0,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "documents_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "employee_assignments" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "item_name" TEXT NOT NULL,
    "serial_number" TEXT,
    "quantity" INTEGER DEFAULT 1,
    "assign_date" DATETIME,
    "return_date" DATETIME,
    "status" TEXT DEFAULT 'active',
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "employee_assignments_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "employee_attendance" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "status" TEXT NOT NULL,
    "description" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "employee_attendance_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "employee_documents" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "file_name" TEXT NOT NULL,
    "file_path" TEXT NOT NULL,
    "file_type" TEXT,
    "category" TEXT,
    "folder" TEXT,
    "issue_date" DATETIME,
    "start_date" DATETIME,
    "expiry_date" DATETIME,
    "is_archived" INTEGER DEFAULT 0,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "employee_documents_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "employee_movements" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "amount" REAL DEFAULT 0,
    "date" DATETIME NOT NULL,
    "description" TEXT,
    "is_paid" INTEGER DEFAULT 0,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "payment_method" TEXT DEFAULT 'cash',
    CONSTRAINT "employee_movements_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "employee_salary_history" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "amount" REAL DEFAULT 0,
    "start_date" DATETIME NOT NULL,
    "end_date" DATETIME,
    "type" TEXT DEFAULT 'initial',
    "description" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "employee_salary_history_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "employees" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "tc_no" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "position" TEXT,
    "department" TEXT,
    "start_date" DATETIME,
    "end_date" DATETIME,
    "salary" REAL DEFAULT 0,
    "status" TEXT DEFAULT 'active',
    "notes" TEXT,
    "image" TEXT,
    "signature_path" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "past_used_leaves" INTEGER DEFAULT 0,
    "birth_date" DATETIME,
    "devir_izin_bakiyesi" INTEGER DEFAULT 0,
    "devir_maas_bakiyesi" REAL DEFAULT 0,
    "devir_tarihi" DATETIME,
    "iban" TEXT,
    "off_days" TEXT DEFAULT '0',
    "allow_login" INTEGER DEFAULT 0,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "employees_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "inspections" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_id" INTEGER NOT NULL,
    "inspection_date" DATETIME NOT NULL,
    "next_inspection" DATETIME,
    "result" TEXT,
    "cost" REAL DEFAULT 0,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "type" TEXT DEFAULT 'traffic',
    "file_path" TEXT,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "inspections_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "insurances" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_id" INTEGER NOT NULL,
    "company" TEXT NOT NULL,
    "policy_no" TEXT,
    "type" TEXT NOT NULL,
    "start_date" DATETIME NOT NULL,
    "end_date" DATETIME NOT NULL,
    "premium" REAL DEFAULT 0,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "file_path" TEXT,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "insurances_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "leaves" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'annual',
    "start_date" DATETIME NOT NULL,
    "end_date" DATETIME NOT NULL,
    "days" REAL DEFAULT 1,
    "hours" REAL,
    "status" TEXT DEFAULT 'approved',
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "leaves_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "maintenances" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "description" TEXT,
    "date" DATETIME NOT NULL,
    "cost" REAL DEFAULT 0,
    "next_km" INTEGER,
    "next_date" DATETIME,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "file_path" TEXT,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "maintenances_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "meal_settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "price_per_person" REAL NOT NULL DEFAULT 0,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "meal_settings_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "meal_tickets" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "person_count" INTEGER NOT NULL DEFAULT 1,
    "price_per_person" REAL DEFAULT 0,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "meal_tickets_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "meal_price_history" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "old_price" REAL NOT NULL DEFAULT 0,
    "new_price" REAL NOT NULL DEFAULT 0,
    "change_date" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "meal_price_history_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "overtimes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "hours" REAL DEFAULT 0,
    "rate" REAL DEFAULT 1.5,
    "amount" REAL DEFAULT 0,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "overtimes_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "recurring_transactions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "method" TEXT DEFAULT 'CASH',
    "amount" REAL NOT NULL,
    "category" TEXT DEFAULT 'Diğer',
    "description" TEXT,
    "frequency" TEXT DEFAULT 'MONTHLY',
    "next_run_date" DATETIME NOT NULL,
    "is_active" INTEGER DEFAULT 1,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "recurring_transactions_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "salaries" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employee_id" INTEGER NOT NULL,
    "period" TEXT NOT NULL,
    "base_salary" REAL DEFAULT 0,
    "bonus" REAL DEFAULT 0,
    "deduction" REAL DEFAULT 0,
    "net_salary" REAL DEFAULT 0,
    "payment_date" DATETIME,
    "salary_month" TEXT,
    "status" TEXT DEFAULT 'pending',
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    "payment_method" TEXT DEFAULT 'cash',
    CONSTRAINT "salaries_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "schema_migrations" (
    "version" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "applied_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "services" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "service_name" TEXT,
    "description" TEXT,
    "date" DATETIME NOT NULL,
    "km" INTEGER,
    "cost" REAL DEFAULT 0,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "file_path" TEXT,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "services_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "transactions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "type" TEXT NOT NULL,
    "category" TEXT,
    "amount" REAL DEFAULT 0,
    "description" TEXT,
    "payment_method" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "method" TEXT DEFAULT 'CASH',
    "check_number" TEXT,
    "check_due_date" DATETIME,
    "status" TEXT DEFAULT 'COMPLETED',
    "currency" TEXT DEFAULT 'TRY',
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "transactions_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "full_name" TEXT,
    "password_hash" TEXT NOT NULL,
    "role" TEXT DEFAULT 'user',
    "role_id" INTEGER,
    "employee_id" INTEGER,
    "permissions" TEXT,
    "status" TEXT DEFAULT 'active',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "must_change_password" INTEGER DEFAULT 0,
    "is_active" INTEGER DEFAULT 1,
    "two_factor_secret" TEXT,
    "two_factor_enabled" INTEGER DEFAULT 0,
    "two_factor_backup_codes" TEXT,
    "recovery_otp" TEXT,
    "recovery_otp_expires_at" DATETIME
)`,
`CREATE TABLE IF NOT EXISTS "vehicles" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "plate" TEXT NOT NULL,
    "brand" TEXT,
    "model" TEXT,
    "year" INTEGER,
    "color" TEXT,
    "status" TEXT DEFAULT 'active',
    "km" INTEGER DEFAULT 0,
    "image" TEXT,
    "notes" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "vehicles_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "work_items" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "work_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "receipt_no" TEXT,
    "vehicle_id" INTEGER,
    "employee_id" INTEGER,
    "custom_vehicle" TEXT,
    "custom_employee" TEXT,
    "start_time" TEXT,
    "end_time" TEXT,
    "hours" REAL DEFAULT 0,
    "overtime_hours" REAL DEFAULT 0,
    "unit_price" REAL DEFAULT 0,
    "travel_price" REAL DEFAULT 0,
    "total_price" REAL DEFAULT 0,
    "description" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "is_archived" INTEGER DEFAULT 0,
    CONSTRAINT "work_items_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "work_items_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "work_items_work_id_fkey" FOREIGN KEY ("work_id") REFERENCES "works" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "works" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "vehicle_id" INTEGER,
    "employee_id" INTEGER,
    "customer_id" INTEGER,
    "customer" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT DEFAULT 'pending',
    "price" REAL DEFAULT 0,
    "location" TEXT,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "start_date" DATETIME,
    "end_date" DATETIME,
    "work_start_time" TEXT DEFAULT '08:00',
    "work_end_time" TEXT DEFAULT '17:00',
    "is_archived" INTEGER DEFAULT 0,
    "pazar_multiplier" REAL DEFAULT 1.5,
    "mesai_multiplier" REAL DEFAULT 1.5,
    "disable_overtime" INTEGER DEFAULT 0,
    "pdf_settings" TEXT,
    CONSTRAINT "works_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "works_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "works_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "works_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "departments" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT DEFAULT 'active',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "departments_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "leave_types" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT DEFAULT 'active',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "leave_types_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "document_categories" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT DEFAULT 'active',
    "target_type" TEXT DEFAULT 'employee',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "document_categories_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "document_folders" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "related_type" TEXT,
    "related_id" INTEGER,
    "is_archived" INTEGER DEFAULT 0,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "document_folders_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "vehicle_types" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "vehicle_types_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "public_holidays" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "description" TEXT,
    "status" TEXT DEFAULT 'active',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "public_holidays_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE INDEX IF NOT EXISTS "idx_assignments_vehicle" ON "assignments"("vehicle_id")`,
`CREATE INDEX IF NOT EXISTS "idx_companies_user" ON "companies"("user_id")`,
`CREATE INDEX IF NOT EXISTS "idx_customers_company" ON "customers"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_employee_assignments_employee" ON "employee_assignments"("employee_id")`,
`CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_employee_attendance_1" ON "employee_attendance"("employee_id", "date")`,
`CREATE INDEX IF NOT EXISTS "idx_employee_documents_employee" ON "employee_documents"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_employee_salary_history_employee" ON "employee_salary_history"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_employees_company" ON "employees"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_inspections_vehicle" ON "inspections"("vehicle_id")`,
`CREATE INDEX IF NOT EXISTS "idx_insurances_vehicle" ON "insurances"("vehicle_id")`,
`CREATE INDEX IF NOT EXISTS "idx_leaves_employee" ON "leaves"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_maintenances_vehicle" ON "maintenances"("vehicle_id")`,
`CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_meal_settings_1" ON "meal_settings"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_overtimes_employee" ON "overtimes"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_salaries_employee" ON "salaries"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_services_vehicle" ON "services"("vehicle_id")`,
`CREATE INDEX IF NOT EXISTS "idx_transactions_date" ON "transactions"("date")`,
`CREATE INDEX IF NOT EXISTS "idx_transactions_company" ON "transactions"("company_id")`,
`CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_users_1" ON "users"("username")`,
`CREATE UNIQUE INDEX IF NOT EXISTS "sqlite_autoindex_users_2" ON "users"("email")`,
`CREATE INDEX IF NOT EXISTS "idx_vehicles_company" ON "vehicles"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_work_items_date" ON "work_items"("date")`,
`CREATE INDEX IF NOT EXISTS "idx_work_items_work" ON "work_items"("work_id")`,
`CREATE INDEX IF NOT EXISTS "idx_works_company" ON "works"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_works_customer" ON "works"("customer_id")`,
`CREATE INDEX IF NOT EXISTS "idx_public_holidays_company" ON "public_holidays"("company_id")`,
`CREATE TABLE IF NOT EXISTS "arvento_history" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "plate" TEXT NOT NULL,
    "device_no" TEXT NOT NULL,
    "lat" REAL NOT NULL,
    "lng" REAL NOT NULL,
    "speed" INTEGER NOT NULL,
    "ignition" INTEGER NOT NULL,
    "heading" INTEGER NOT NULL,
    "gps_date" DATETIME NOT NULL,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE INDEX IF NOT EXISTS "idx_arvento_history_plate" ON "arvento_history"("plate")`,
`CREATE INDEX IF NOT EXISTS "idx_arvento_history_gps_date" ON "arvento_history"("gps_date")`,
`CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER,
    "user_id" INTEGER,
    "username" TEXT,
    "user_role" TEXT,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT,
    "entity_name" TEXT,
    "description" TEXT NOT NULL,
    "details" TEXT,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "severity" TEXT DEFAULT 'info',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "audit_logs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "roles" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "color" TEXT DEFAULT '#3b82f6',
    "is_system" INTEGER DEFAULT 0,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "roles_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "permissions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "role_id" INTEGER NOT NULL,
    "module" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "allowed" INTEGER DEFAULT 0,
    CONSTRAINT "permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "requests" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "company_id" INTEGER NOT NULL,
    "employee_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "status" TEXT DEFAULT 'pending',
    "details" TEXT NOT NULL,
    "notes" TEXT,
    "rejection_reason" TEXT,
    "created_by_id" INTEGER,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "requests_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "requests_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "requests_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "request_approvals" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "request_id" INTEGER NOT NULL,
    "approver_id" INTEGER,
    "step" INTEGER DEFAULT 1,
    "status" TEXT NOT NULL,
    "comment" TEXT,
    "action_date" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "request_approvals_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "requests" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "request_approvals_approver_id_fkey" FOREIGN KEY ("approver_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "system_announcements" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "type" TEXT DEFAULT 'info',
    "company_id" INTEGER,
    "created_by" INTEGER,
    "is_active" INTEGER DEFAULT 1,
    "is_dismissible" INTEGER DEFAULT 1,
    "show_popup" INTEGER DEFAULT 0,
    "expires_at" DATETIME,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "company_settings" (
    "company_id" INTEGER NOT NULL PRIMARY KEY,
    "settings_json" TEXT NOT NULL,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "user_preferences" (
    "user_id" INTEGER NOT NULL PRIMARY KEY,
    "preferences_json" TEXT NOT NULL,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "revoked_sessions" (
    "session_id" TEXT NOT NULL PRIMARY KEY,
    "user_id" INTEGER,
    "revoked_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "reason" TEXT,
    "expires_at" DATETIME
)`,
`CREATE TABLE IF NOT EXISTS "user_company_access" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER NOT NULL,
    "company_id" INTEGER NOT NULL,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "user_company_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "user_company_access_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "user_permissions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER NOT NULL,
    "vehicles" TEXT DEFAULT 'crud',
    "employees" TEXT DEFAULT 'crud',
    "finance" TEXT DEFAULT 'crud',
    "works" TEXT DEFAULT 'crud',
    "settings" TEXT DEFAULT 'none',
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "user_permissions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
)`,
`CREATE TABLE IF NOT EXISTS "company_notification_settings" (
    "company_id" INTEGER NOT NULL PRIMARY KEY,
    "settings_json" TEXT NOT NULL,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "user_notification_settings" (
    "user_id" INTEGER NOT NULL PRIMARY KEY,
    "settings_json" TEXT NOT NULL,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "email_settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smtp_host" TEXT,
    "smtp_port" INTEGER DEFAULT 587,
    "smtp_secure" INTEGER DEFAULT 0,
    "smtp_user" TEXT,
    "smtp_pass" TEXT,
    "sender_name" TEXT DEFAULT '⚡ Kontrol Güvenlik Ekibi',
    "sender_email" TEXT DEFAULT 'noreply@kontrol-app.com',
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP
)`,
`CREATE TABLE IF NOT EXISTS "email_templates" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "type" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "html_content" TEXT NOT NULL,
    "description" TEXT,
    "updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "sender_name" TEXT DEFAULT 'Kontrol'
)`,
`CREATE INDEX IF NOT EXISTS "idx_audit_company" ON "audit_logs"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_audit_user" ON "audit_logs"("user_id")`,
`CREATE INDEX IF NOT EXISTS "idx_audit_created" ON "audit_logs"("created_at")`,
`CREATE INDEX IF NOT EXISTS "idx_roles_company" ON "roles"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_permissions_role" ON "permissions"("role_id")`,
`CREATE INDEX IF NOT EXISTS "idx_requests_company" ON "requests"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_requests_employee" ON "requests"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_requests_created_by" ON "requests"("created_by_id")`,
`CREATE INDEX IF NOT EXISTS "idx_requests_status" ON "requests"("status")`,
`CREATE INDEX IF NOT EXISTS "idx_request_approvals_request" ON "request_approvals"("request_id")`,
`CREATE INDEX IF NOT EXISTS "idx_announcements_company" ON "system_announcements"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_announcements_active" ON "system_announcements"("is_active")`,
`CREATE INDEX IF NOT EXISTS "idx_revoked_sessions_expires" ON "revoked_sessions"("expires_at")`,
`CREATE INDEX IF NOT EXISTS "idx_user_company_access_user" ON "user_company_access"("user_id")`,
`CREATE INDEX IF NOT EXISTS "idx_user_company_access_company" ON "user_company_access"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_user_permissions_user" ON "user_permissions"("user_id")`,
`CREATE INDEX IF NOT EXISTS "idx_work_items_employee" ON "work_items"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_work_items_vehicle" ON "work_items"("vehicle_id")`,
`CREATE INDEX IF NOT EXISTS "idx_works_employee" ON "works"("employee_id")`,
`CREATE INDEX IF NOT EXISTS "idx_works_vehicle" ON "works"("vehicle_id")`,
`CREATE INDEX IF NOT EXISTS "idx_departments_company" ON "departments"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_leave_types_company" ON "leave_types"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_doc_categories_company" ON "document_categories"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_doc_folders_company" ON "document_folders"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_vehicle_types_company" ON "vehicle_types"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_meal_tickets_company" ON "meal_tickets"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_meal_price_history_company" ON "meal_price_history"("company_id")`,
`CREATE INDEX IF NOT EXISTS "idx_documents_vehicle" ON "documents"("vehicle_id")`,
];

module.exports = { allTablesSQL };