
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.10.0
 * Query Engine version: 0edf323efd1d98336f3f0a68684b56f689b900d3
 */
Prisma.prismaVersion = {
  client: "7.10.0",
  engine: "0edf323efd1d98336f3f0a68684b56f689b900d3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AssignmentsScalarFieldEnum = {
  id: 'id',
  vehicle_id: 'vehicle_id',
  item_name: 'item_name',
  quantity: 'quantity',
  assigned_to: 'assigned_to',
  department: 'department',
  start_date: 'start_date',
  end_date: 'end_date',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.CompaniesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  name: 'name',
  tax_number: 'tax_number',
  tax_office: 'tax_office',
  sgk_no: 'sgk_no',
  address: 'address',
  phone: 'phone',
  signature_path: 'signature_path',
  stamp_path: 'stamp_path',
  plan: 'plan',
  status: 'status',
  expires_at: 'expires_at',
  max_vehicles: 'max_vehicles',
  max_employees: 'max_employees',
  max_users: 'max_users',
  storage_limit_mb: 'storage_limit_mb',
  created_at: 'created_at'
};

exports.Prisma.CustomersScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  phone: 'phone',
  email: 'email',
  address: 'address',
  tax_number: 'tax_number',
  tax_office: 'tax_office',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.DocumentsScalarFieldEnum = {
  id: 'id',
  vehicle_id: 'vehicle_id',
  related_type: 'related_type',
  related_id: 'related_id',
  file_name: 'file_name',
  file_path: 'file_path',
  file_type: 'file_type',
  doc_type: 'doc_type',
  category: 'category',
  folder: 'folder',
  start_date: 'start_date',
  end_date: 'end_date',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Employee_assignmentsScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  item_name: 'item_name',
  serial_number: 'serial_number',
  quantity: 'quantity',
  assign_date: 'assign_date',
  return_date: 'return_date',
  status: 'status',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Employee_attendanceScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  date: 'date',
  status: 'status',
  description: 'description',
  created_at: 'created_at'
};

exports.Prisma.Employee_documentsScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  file_name: 'file_name',
  file_path: 'file_path',
  file_type: 'file_type',
  category: 'category',
  folder: 'folder',
  issue_date: 'issue_date',
  start_date: 'start_date',
  expiry_date: 'expiry_date',
  is_archived: 'is_archived',
  created_at: 'created_at'
};

exports.Prisma.Employee_movementsScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  type: 'type',
  amount: 'amount',
  date: 'date',
  description: 'description',
  is_paid: 'is_paid',
  created_at: 'created_at',
  payment_method: 'payment_method'
};

exports.Prisma.Employee_salary_historyScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  amount: 'amount',
  start_date: 'start_date',
  end_date: 'end_date',
  type: 'type',
  description: 'description',
  created_at: 'created_at'
};

exports.Prisma.EmployeesScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  first_name: 'first_name',
  last_name: 'last_name',
  tc_no: 'tc_no',
  phone: 'phone',
  email: 'email',
  position: 'position',
  department: 'department',
  start_date: 'start_date',
  end_date: 'end_date',
  salary: 'salary',
  status: 'status',
  notes: 'notes',
  image: 'image',
  signature_path: 'signature_path',
  is_archived: 'is_archived',
  created_at: 'created_at',
  past_used_leaves: 'past_used_leaves',
  birth_date: 'birth_date',
  devir_izin_bakiyesi: 'devir_izin_bakiyesi',
  devir_maas_bakiyesi: 'devir_maas_bakiyesi',
  devir_tarihi: 'devir_tarihi',
  iban: 'iban',
  off_days: 'off_days'
};

exports.Prisma.InspectionsScalarFieldEnum = {
  id: 'id',
  vehicle_id: 'vehicle_id',
  inspection_date: 'inspection_date',
  next_inspection: 'next_inspection',
  result: 'result',
  cost: 'cost',
  notes: 'notes',
  created_at: 'created_at',
  type: 'type',
  file_path: 'file_path',
  is_archived: 'is_archived'
};

exports.Prisma.InsurancesScalarFieldEnum = {
  id: 'id',
  vehicle_id: 'vehicle_id',
  company: 'company',
  policy_no: 'policy_no',
  type: 'type',
  start_date: 'start_date',
  end_date: 'end_date',
  premium: 'premium',
  notes: 'notes',
  created_at: 'created_at',
  file_path: 'file_path',
  is_archived: 'is_archived'
};

exports.Prisma.LeavesScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  type: 'type',
  start_date: 'start_date',
  end_date: 'end_date',
  days: 'days',
  hours: 'hours',
  status: 'status',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.MaintenancesScalarFieldEnum = {
  id: 'id',
  vehicle_id: 'vehicle_id',
  type: 'type',
  description: 'description',
  date: 'date',
  cost: 'cost',
  next_km: 'next_km',
  next_date: 'next_date',
  notes: 'notes',
  created_at: 'created_at',
  file_path: 'file_path',
  is_archived: 'is_archived'
};

exports.Prisma.Meal_settingsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  price_per_person: 'price_per_person',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Meal_ticketsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  date: 'date',
  person_count: 'person_count',
  price_per_person: 'price_per_person',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Meal_price_historyScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  old_price: 'old_price',
  new_price: 'new_price',
  change_date: 'change_date'
};

exports.Prisma.OvertimesScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  date: 'date',
  hours: 'hours',
  rate: 'rate',
  amount: 'amount',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Recurring_transactionsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  type: 'type',
  method: 'method',
  amount: 'amount',
  category: 'category',
  description: 'description',
  frequency: 'frequency',
  next_run_date: 'next_run_date',
  is_active: 'is_active',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.SalariesScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  period: 'period',
  base_salary: 'base_salary',
  bonus: 'bonus',
  deduction: 'deduction',
  net_salary: 'net_salary',
  payment_date: 'payment_date',
  salary_month: 'salary_month',
  status: 'status',
  payment_method: 'payment_method',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Schema_migrationsScalarFieldEnum = {
  version: 'version',
  applied_at: 'applied_at'
};

exports.Prisma.ServicesScalarFieldEnum = {
  id: 'id',
  vehicle_id: 'vehicle_id',
  type: 'type',
  service_name: 'service_name',
  description: 'description',
  date: 'date',
  km: 'km',
  cost: 'cost',
  notes: 'notes',
  created_at: 'created_at',
  file_path: 'file_path',
  is_archived: 'is_archived'
};

exports.Prisma.TransactionsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  date: 'date',
  type: 'type',
  category: 'category',
  amount: 'amount',
  description: 'description',
  payment_method: 'payment_method',
  created_at: 'created_at',
  method: 'method',
  check_number: 'check_number',
  check_due_date: 'check_due_date',
  status: 'status',
  currency: 'currency',
  is_archived: 'is_archived'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  full_name: 'full_name',
  password_hash: 'password_hash',
  created_at: 'created_at',
  role: 'role',
  role_id: 'role_id',
  employee_id: 'employee_id',
  permissions: 'permissions',
  must_change_password: 'must_change_password',
  is_active: 'is_active',
  two_factor_secret: 'two_factor_secret',
  two_factor_enabled: 'two_factor_enabled',
  two_factor_backup_codes: 'two_factor_backup_codes'
};

exports.Prisma.VehiclesScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  type: 'type',
  plate: 'plate',
  brand: 'brand',
  model: 'model',
  year: 'year',
  color: 'color',
  status: 'status',
  km: 'km',
  image: 'image',
  notes: 'notes',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.Work_itemsScalarFieldEnum = {
  id: 'id',
  work_id: 'work_id',
  date: 'date',
  receipt_no: 'receipt_no',
  vehicle_id: 'vehicle_id',
  employee_id: 'employee_id',
  custom_vehicle: 'custom_vehicle',
  custom_employee: 'custom_employee',
  start_time: 'start_time',
  end_time: 'end_time',
  hours: 'hours',
  overtime_hours: 'overtime_hours',
  unit_price: 'unit_price',
  travel_price: 'travel_price',
  total_price: 'total_price',
  description: 'description',
  created_at: 'created_at',
  is_archived: 'is_archived'
};

exports.Prisma.WorksScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  vehicle_id: 'vehicle_id',
  employee_id: 'employee_id',
  customer_id: 'customer_id',
  customer: 'customer',
  title: 'title',
  description: 'description',
  status: 'status',
  price: 'price',
  location: 'location',
  created_at: 'created_at',
  start_date: 'start_date',
  end_date: 'end_date',
  work_start_time: 'work_start_time',
  work_end_time: 'work_end_time',
  is_archived: 'is_archived',
  pazar_multiplier: 'pazar_multiplier',
  mesai_multiplier: 'mesai_multiplier',
  pdf_settings: 'pdf_settings'
};

exports.Prisma.DepartmentsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Leave_typesScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Document_categoriesScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  status: 'status',
  target_type: 'target_type',
  created_at: 'created_at'
};

exports.Prisma.Document_foldersScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  related_type: 'related_type',
  related_id: 'related_id',
  is_archived: 'is_archived',
  created_at: 'created_at'
};

exports.Prisma.Vehicle_typesScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  created_at: 'created_at'
};

exports.Prisma.Public_holidaysScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  date: 'date',
  description: 'description',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.RolesScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  name: 'name',
  description: 'description',
  created_at: 'created_at'
};

exports.Prisma.PermissionsScalarFieldEnum = {
  id: 'id',
  role_id: 'role_id',
  module: 'module',
  can_read: 'can_read',
  can_create: 'can_create',
  can_update: 'can_update',
  can_delete: 'can_delete',
  can_approve: 'can_approve',
  scope: 'scope'
};

exports.Prisma.RequestsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  created_by_id: 'created_by_id',
  employee_id: 'employee_id',
  type: 'type',
  title: 'title',
  description: 'description',
  request_data: 'request_data',
  status: 'status',
  current_step: 'current_step',
  total_steps: 'total_steps',
  document_path: 'document_path',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Request_approvalsScalarFieldEnum = {
  id: 'id',
  request_id: 'request_id',
  approver_id: 'approver_id',
  step: 'step',
  status: 'status',
  comment: 'comment',
  action_date: 'action_date'
};

exports.Prisma.System_announcementsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  message: 'message',
  type: 'type',
  company_id: 'company_id',
  created_by: 'created_by',
  is_active: 'is_active',
  is_dismissible: 'is_dismissible',
  show_popup: 'show_popup',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Audit_logsScalarFieldEnum = {
  id: 'id',
  company_id: 'company_id',
  user_id: 'user_id',
  username: 'username',
  user_role: 'user_role',
  action: 'action',
  entity_type: 'entity_type',
  entity_id: 'entity_id',
  entity_name: 'entity_name',
  description: 'description',
  details: 'details',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  severity: 'severity',
  created_at: 'created_at'
};

exports.Prisma.Company_settingsScalarFieldEnum = {
  company_id: 'company_id',
  settings_json: 'settings_json',
  updated_at: 'updated_at'
};

exports.Prisma.User_preferencesScalarFieldEnum = {
  user_id: 'user_id',
  preferences_json: 'preferences_json',
  updated_at: 'updated_at'
};

exports.Prisma.Revoked_sessionsScalarFieldEnum = {
  session_id: 'session_id',
  user_id: 'user_id',
  revoked_at: 'revoked_at',
  reason: 'reason',
  expires_at: 'expires_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  assignments: 'assignments',
  companies: 'companies',
  customers: 'customers',
  documents: 'documents',
  employee_assignments: 'employee_assignments',
  employee_attendance: 'employee_attendance',
  employee_documents: 'employee_documents',
  employee_movements: 'employee_movements',
  employee_salary_history: 'employee_salary_history',
  employees: 'employees',
  inspections: 'inspections',
  insurances: 'insurances',
  leaves: 'leaves',
  maintenances: 'maintenances',
  meal_settings: 'meal_settings',
  meal_tickets: 'meal_tickets',
  meal_price_history: 'meal_price_history',
  overtimes: 'overtimes',
  recurring_transactions: 'recurring_transactions',
  salaries: 'salaries',
  schema_migrations: 'schema_migrations',
  services: 'services',
  transactions: 'transactions',
  users: 'users',
  vehicles: 'vehicles',
  work_items: 'work_items',
  works: 'works',
  departments: 'departments',
  leave_types: 'leave_types',
  document_categories: 'document_categories',
  document_folders: 'document_folders',
  vehicle_types: 'vehicle_types',
  public_holidays: 'public_holidays',
  roles: 'roles',
  permissions: 'permissions',
  requests: 'requests',
  request_approvals: 'request_approvals',
  system_announcements: 'system_announcements',
  audit_logs: 'audit_logs',
  company_settings: 'company_settings',
  user_preferences: 'user_preferences',
  revoked_sessions: 'revoked_sessions'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
